name: lfti_app
description: Workout tracking app

version: 1.1.1+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  intl: ^0.16.1
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  firebase_database: ^3.1.3
  cloud_firestore: ^0.13.4+2
  dotted_border: ^1.0.5
  numberpicker: ^1.2.0
  flutter_launcher_icons: ^0.7.4
  shared_preferences: ^0.5.6+3
  charts_flutter: ^0.9.0
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: SF-Pro-Compact-Rounded-Semibold
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.ttf
