name: exercises_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  uuid: ^4.1.0
  meta: ^1.9.1
  json_annotation: ^4.8.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  json_serializable: ^6.7.1
  test: ^1.24.8
  build_runner: ^2.4.6
